# Generated by Django 2.1.1 on 2018-09-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mathFunctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='recursiveFunctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_one', models.CharField(max_length=50)),
                ('field_two', models.CharField(max_length=50)),
                ('math_function', models.CharField(max_length=50)),
            ],
        ),
    ]
