# Generated by Django 2.1.1 on 2018-09-20 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursiveapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursivefunctions',
            name='math_function',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='recursiveapp.mathFunctions'),
        ),
    ]
