# Generated by Django 2.1.1 on 2018-09-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursiveapp', '0003_recursivefunctions_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursivefunctions',
            name='name',
            field=models.CharField(default='name', max_length=50, unique=True),
        ),
    ]
